// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mlnOeISnwLI5bquYh9I9KYiIX2O-JyE',
    appId: '1:197203428484:web:4dd4ee6fb5d09eff026ed1',
    messagingSenderId: '197203428484',
    projectId: 'cmsc-156-final-project',
    authDomain: 'cmsc-156-final-project.firebaseapp.com',
    storageBucket: 'cmsc-156-final-project.appspot.com',
    measurementId: 'G-HJGFFHRXEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjOssa5fFlw8bS9wuwfLCtzle_DvD6Wc',
    appId: '1:197203428484:android:31bfede4a842fe1b026ed1',
    messagingSenderId: '197203428484',
    projectId: 'cmsc-156-final-project',
    storageBucket: 'cmsc-156-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDicaPNgndh7tpyH-OYwriJcd3evyoFFAM',
    appId: '1:197203428484:ios:fd13dd22b3211418026ed1',
    messagingSenderId: '197203428484',
    projectId: 'cmsc-156-final-project',
    storageBucket: 'cmsc-156-final-project.appspot.com',
    iosBundleId: 'com.example.dicedicedice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDicaPNgndh7tpyH-OYwriJcd3evyoFFAM',
    appId: '1:197203428484:ios:fd13dd22b3211418026ed1',
    messagingSenderId: '197203428484',
    projectId: 'cmsc-156-final-project',
    storageBucket: 'cmsc-156-final-project.appspot.com',
    iosBundleId: 'com.example.dicedicedice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5mlnOeISnwLI5bquYh9I9KYiIX2O-JyE',
    appId: '1:197203428484:web:4fe4507d66976a85026ed1',
    messagingSenderId: '197203428484',
    projectId: 'cmsc-156-final-project',
    authDomain: 'cmsc-156-final-project.firebaseapp.com',
    storageBucket: 'cmsc-156-final-project.appspot.com',
    measurementId: 'G-9M4HYVZKC8',
  );

}